name: foop_loyalty_plugin
description: A loyalty management tool
version: 0.6.1
homepage: https://github.com/savilmehra/foop_loyalty_plugin

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  http: ^0.13.3
  path: ^1.8.0
  url_launcher: ^6.0.9
  fluttertoast: ^8.0.8
  flutter_bloc: ^8.0.0


  shared_preferences: ^2.0.7
  get_it: ^7.2.0
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.1.0
  html_editor_enhanced: ^2.4.0+1
  image_picker: ^0.8.4+1
  image_cropper: ^1.4.1
  file_picker: ^4.2.1
  mime: ^1.0.0
  camera: ^0.9.4+3
  html: ^0.15.0
  pinch_zoom: ^1.0.0
  video_player: ^2.1.12
  timeago: ^3.1.0
  intl: ^0.17.0
  http_parser: ^4.0.0
  flutter_widget_from_html_core: ^0.8.5+1
  flutter_quill: ^3.2.0
  percent_indicator: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/appimages/
    - assets/lang/

  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: foop.loyalty.plugin.foop_loyalty_plugin
        pluginClass: FoopLoyaltyPlugin
      ios:
        pluginClass: FoopLoyaltyPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
